name: Run API Tests with Newman

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›’ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ“¦ Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: ðŸ“¥ Install Newman & HTML reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: ðŸ§ª Run API tests with Newman
        run: |
          mkdir -p reports
          newman run tests/brand/brand.postman_collection.json \
            -d tests/brand/product.csv \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/brand-report.html

      - name: ðŸ“¤ Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: brand-api-test-report
          path: reports/brand-report.html
